version: "3.8"

services:
  nginx-example:
    container_name: contohaja
    image: nginx:latest
  nginx-example2:
    container_name: nginx-example2
    image: nginx:latest
    ports:
      - "8080:80"