version: "3.9"

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-restart
    restart: always
    ports:
      - "27012:27012"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Rangga
      MONGO_INITDB_ROOT_PASSWORD: Rangga
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-restart
    restart: always
    depends_on:
      - mongodb-example
    ports:
      - "8088:8088"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Rangga
      ME_CONFIG_MONGODB_ADMINPASSWORD: Rangga
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network_example

networks:
  network_example:
    driver: bridge
